require 'test_helper'

class CouponTest < ActiveSupport::TestCase
  # test "the truth" do
  #   assert true
  # end
  
  puts "Create example coupon with code: '307280967206173391266848696493937455594', date: '2015-05-15'"
  
  def setup
    @coupon = Coupon.new(code: "1231231234123", date: "2015-05-15")
  end
  
  puts "Only test, validation test, since the code is generated by database. Therefore, no change."
  test "test valid" do
    assert @coupon.valid?, "invalid coupon"
  end
end
